### ISSUE TITLE
Orthographe

### ISSUE THREAD

**Issue by Kirby56** [goldobot/ELEC#1]
Bonjour,
Je vous propose de corriger les quelques fautes d'orthographe dans votre texte,
cordialement

**Comment by alfarobase** [comment]
Quelle partie vous semble nécessiter des corrections? et pour quelle raisons souhaitez-vous contribuer?

**Comment by Kirby56** [comment]
il s'agit de la partie  ELEC/1-LIB/read-me - last update 19-03-2017.txt
c'est dans le cadre d'un projet de mon école ou on doit contribuer a plusieurs projet de github d'une facon ou d'une autre !

**Comment by alfarobase** [comment]
Ok (merge accepté), mais peut-être serait-il intéressant dans le cadre de votre formation d'aller au delà des corrections orthographique, disposez-vous du logiciel altium?
